language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
# command to install wxPython using apt
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-wxgtk2.8
install:
    #- sudo apt-get install python-wxgtk2.8 python-wxtools wx2.8-i18n libwxgtk2.8-dev libgtk2.0-dev
    - cd taskcoach
    - make prepare
    - python taskcoach.py
# command to run tests
script: 
    - cd taskcoach
    - make unittests